<a href="https://colab.research.google.com/github/shivani14012004/course-of-python/blob/main/Npy_Indexing_slicing08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#*Numpy Operation

In [1]:
#Iterview Questions
#Create an array of 4x4 zeros
import numpy as np

np.zeros((4,4))  #float

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.full((4,4),0)  #integer

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
np.full((4,4),0,dtype=bool)  #0 is False

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [5]:
np.full((4,4),0,dtype=complex)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [6]:
#create an array with constant value
np.full((4,4),0,dtype=str)

array([['0', '0', '0', '0'],
       ['0', '0', '0', '0'],
       ['0', '0', '0', '0'],
       ['0', '0', '0', '0']], dtype='<U1')

In [7]:
np.full((4,4),-11,dtype=float)

array([[-11., -11., -11., -11.],
       [-11., -11., -11., -11.],
       [-11., -11., -11., -11.],
       [-11., -11., -11., -11.]])

In [ ]:
#only we can work on numeric problems

In [9]:
np.full((4,4),10,dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
#Interview Question
#Create a numpy array of 4X4 with diagonal elements as True and Non diagonal element as False
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.identity(5) #Square Matrix -2D

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
#In python except 0",None,[],() everything is True
np.identity(5,dtype=bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [13]:
bool(None)

False

In [14]:
bool(0)

False

In [17]:
bool(234)

True

In [18]:
#Create a numpy array of 4X4 with diagonal elements as False and Non diagonal element as True

~np.identity(5,dtype=bool)

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [20]:
#access diagonal elements of numpy array
s=np.identity(5)
s.diagonal()

array([1., 1., 1., 1., 1.])

#Numpy Slicing and Indexing

In [23]:
x=np.arange(24).reshape((6,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
#Using index we can access one row at a time
x[3]

array([12, 13, 14, 15])

In [25]:
#row with element index
#1)
x[3][3]

np.int64(15)

In [26]:
#2)
x[3,3]

np.int64(15)

In [27]:
#Examples
x[2]

array([ 8,  9, 10, 11])

In [28]:
x[2,3]

np.int64(11)

In [29]:
x[2][3]

np.int64(11)

In [30]:
#Numpy array is mutable in nature
x[3][3]

np.int64(15)

In [31]:
#replace 15 by 50
x[3,3]=50
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
#access more rows
x[:]#[start_index : stop_index]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
x[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50]])

In [36]:
x[3:] #+ve

array([[12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
x[-3:] #-ve

array([[12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
x[::-3]

array([[20, 21, 22, 23],
       [ 8,  9, 10, 11]])

In [40]:
x[::-2]

array([[20, 21, 22, 23],
       [12, 13, 14, 50],
       [ 4,  5,  6,  7]])

In [41]:
x[::-4]

array([[20, 21, 22, 23],
       [ 4,  5,  6,  7]])

In [42]:
#column operation
x[-2:,:] #[row,column]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
x[-2:,-2:]

array([[18, 19],
       [22, 23]])

In [57]:
x[-3:-1,:-2]

array([[12, 13],
       [16, 17]])

In [52]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
#[start:stop:step]
x[2:4,::3]

array([[ 8, 11],
       [12, 50]])