<a href="https://colab.research.google.com/github/shivani14012004/course-of-python/blob/main/Numpy06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#*Numpy

In [2]:
import numpy as np

In [ ]:
#background structure is Array of numpy
#suporting indexing and silicing

#1Dimensional
a=np.array([20,10,99,30,100])
a

array([ 20,  10,  99,  30, 100])

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [ ]:
np.__version__

'2.0.2'

In [ ]:
a

array([ 20,  10,  99,  30, 100])

In [ ]:
#find max number
a.max()


np.int64(100)

In [ ]:
print(a.max())

100


In [ ]:
a.min()

np.int64(10)

In [ ]:
#How many elements present
#It is used in Debugging

a.size

5

In [ ]:
#dimension
a.ndim

1

In [ ]:
#Numpy datatype to check
type(a)

numpy.ndarray

In [ ]:
#Q1)What is type of Numpy array?--> ndaaray


In [3]:
b = np.array([[10,20,1],
              [-1,5,9],
              [7,40,2]])

In [4]:
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [5]:
b.ndim

2

In [6]:
#to check number of rows and column

b.shape   #(rows,column)

(3, 3)

In [7]:
#addition of all element
print(b.sum())

93


In [8]:
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [9]:
#addition in row wise and column wise
#columnwise addition

print(b.sum(axis=0))

[16 65 12]


In [10]:
#rowwise addition
print(b.sum(axis=1))

[31 13 49]


In [ ]:
#Assignment:b.min(),b.max(),b.mean(),b.std()

In [11]:
print(b.min())

-1


In [15]:
print(b.min(axis=0))

[-1  5  1]


In [19]:
print(b.min(axis=1))

[ 1 -1  2]


In [12]:
print(b.max())

40


In [20]:
print(b.max(axis=0))

[10 40  9]


In [21]:
print(b.max(axis=1))

[20  9 40]


In [13]:
print(b.mean())

10.333333333333334


In [18]:
print(b.mean(axis=0))

[ 5.33333333 21.66666667  4.        ]


In [22]:
print(b.mean(axis=1))

[10.33333333  4.33333333 16.33333333]


In [14]:
print(b.std())

12.01850425154663


In [ ]:
a.ndim #1D

1

In [ ]:
b.ndim #2D

2

##**Different ways to creating numpy arrays

In [ ]:
#numpy array with random numbers

np.random.random(5) #1D


array([0.38907165, 0.27257347, 0.70987221, 0.08295453, 0.69684777])

In [ ]:

np.random.random((5,5))

array([[0.9747553 , 0.20034313, 0.84038163, 0.67978557, 0.21370367],
       [0.84881454, 0.96301871, 0.97056878, 0.13892489, 0.77819398],
       [0.25066411, 0.76124213, 0.95803835, 0.79063905, 0.19801017],
       [0.80530559, 0.7175375 , 0.2927877 , 0.09830427, 0.55581659],
       [0.45934299, 0.39456278, 0.41886122, 0.55675936, 0.90580743]])

In [ ]:
np.random.random((5,3)) #2D

array([[0.45806796, 0.20731797, 0.25309322],
       [0.21990554, 0.93147633, 0.1103736 ],
       [0.20545599, 0.24176467, 0.80574019],
       [0.62630331, 0.86556169, 0.67903088],
       [0.66218849, 0.0870747 , 0.27444704]])

In [ ]:
#3D (block,rows,column)

np.random.random((2,2,2))

array([[[0.89182879, 0.41763039],
        [0.34347677, 0.2866609 ]],

       [[0.16926247, 0.59172732],
        [0.02544053, 0.23079152]]])

In [ ]:
np.random

<module 'numpy.random' from '/usr/local/lib/python3.12/dist-packages/numpy/random/__init__.py'>

In [ ]:
#generate array with sequence of numbers

c=np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
c.size

24

In [ ]:
#Q1)convert from 1D to 2D
#use reshape()-->Tempory
#6x4,8X3,12x2,1x24

c.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
c.reshape((8,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
#resize() used for parmnt,changes in dimension
c.resize((3,8))

In [ ]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
c.shape

(3, 8)

In [ ]:
#convert nD to 1D -->TEMP

c.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])